# Generated by Django 5.0.14 on 2026-02-03 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_client_remove_device_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterField(
            model_name='device',
            name='activation_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
