# Generated by Django 5.0.14 on 2026-02-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='identifier',
            new_name='device_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.branch'),
        ),
    ]
