# Generated by Django 5.0.14 on 2026-02-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_paid_until_alter_device_activation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=50)),
                ('draw_date', models.DateField()),
                ('draw_time', models.TimeField()),
                ('number', models.CharField(max_length=10)),
                ('zodiac', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='currentresult',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_time'), name='uniq_provider_draw_time'),
        ),
        migrations.AddField(
            model_name='resultarchive',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider'),
        ),
        migrations.AddIndex(
            model_name='resultarchive',
            index=models.Index(fields=['draw_date', 'provider'], name='core_result_draw_da_6ec9d9_idx'),
        ),
    ]
