# Generated by Django 5.0.14 on 2026-02-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resultarchive_currentresult_uniq_provider_draw_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentresult',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
