# Generated by Django 5.0.14 on 2026-02-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_currentresult_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentresult',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='currentresult',
            name='uniq_provider_draw_time',
        ),
    ]
