# Generated by Django 5.0.14 on 2026-02-05 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animalitoresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentresult',
            options={'ordering': ['provider__name', 'draw_time']},
        ),
        migrations.AddField(
            model_name='currentresult',
            name='draw_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='currentresult',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_date', 'draw_time'), name='uniq_provider_draw_date_time'),
        ),
    ]
