# Generated by Django 5.0.14 on 2026-02-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_currentresult_options_currentresult_draw_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultarchive',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resultarchive',
            index=models.Index(fields=['variant', 'draw_date'], name='core_result_variant_016e27_idx'),
        ),
    ]
