# Generated by Django 5.0.14 on 2026-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resultarchive_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
