# Generated by Django 5.0.14 on 2026-02-06 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_provider_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultarchive',
            options={'ordering': ['provider__name', 'draw_date', 'draw_time']},
        ),
        migrations.RemoveConstraint(
            model_name='currentresult',
            name='uniq_provider_draw_date_time',
        ),
        migrations.RemoveIndex(
            model_name='resultarchive',
            name='core_result_draw_da_6ec9d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='resultarchive',
            name='core_result_variant_016e27_idx',
        ),
        migrations.RenameField(
            model_name='resultarchive',
            old_name='number',
            new_name='winning_number',
        ),
        migrations.RemoveField(
            model_name='resultarchive',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='resultarchive',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='resultarchive',
            name='zodiac',
        ),
        migrations.AddField(
            model_name='resultarchive',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='currentresult',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_results', to='core.provider'),
        ),
        migrations.AlterField(
            model_name='resultarchive',
            name='draw_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='resultarchive',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_results', to='core.provider'),
        ),
        migrations.AddConstraint(
            model_name='currentresult',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_date', 'draw_time'), name='uniq_current_provider_draw_date_time'),
        ),
        migrations.AddConstraint(
            model_name='resultarchive',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_date', 'draw_time'), name='uniq_archive_provider_draw_date_time'),
        ),
    ]
