# Generated by Django 5.0.14 on 2026-02-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_resultarchive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalitoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('draw_time', models.TimeField()),
                ('animal_number', models.PositiveSmallIntegerField()),
                ('animal_name', models.CharField(max_length=50)),
                ('animal_image_url', models.URLField(blank=True)),
                ('provider_logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalito_archives', to='core.provider')),
            ],
            options={
                'ordering': ['provider__name', 'draw_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='animalitoarchive',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_date', 'draw_time'), name='uniq_archive_provider_animalito_draw'),
        ),
    ]
