# Generated by Django 5.0.14 on 2026-02-08 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_animalitoarchive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalitoarchive',
            options={'ordering': ['provider__name', 'draw_date', 'draw_time']},
        ),
        migrations.RemoveConstraint(
            model_name='animalitoarchive',
            name='uniq_archive_provider_animalito_draw',
        ),
        migrations.AlterField(
            model_name='animalitoarchive',
            name='animal_image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='animalitoarchive',
            name='draw_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='animalitoarchive',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_animalitos', to='core.provider'),
        ),
        migrations.AlterField(
            model_name='animalitoarchive',
            name='provider_logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='animalitoarchive',
            constraint=models.UniqueConstraint(fields=('provider', 'draw_date', 'draw_time'), name='uniq_animalito_archive_provider_date_time'),
        ),
    ]
