# Generated by Django 5.0.14 on 2026-02-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_animalitoarchive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalitoarchive',
            name='animal_number',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='animalitoresult',
            name='animal_number',
            field=models.CharField(max_length=2),
        ),
    ]
