# Generated by Django 5.0.14 on 2026-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentresult',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultarchive',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
