# Generated by Django 5.0.14 on 2026-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_currentresult_extra_resultarchive_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
