# Generated by Django 5.0.14 on 2026-03-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_currentresult_extra_resultarchive_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_load_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_reported_message', models.TextField(blank=True, default='')),
                ('last_low_memory_at', models.DateTimeField(blank=True, null=True)),
                ('android_version', models.CharField(blank=True, default='', max_length=64)),
                ('webview_version', models.CharField(blank=True, default='', max_length=128)),
                ('device_model', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('last_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshot', to='core.device')),
            ],
            options={
                'verbose_name': 'Device telemetry snapshot',
                'verbose_name_plural': 'Device telemetry snapshots',
                'ordering': ['device__activation_code'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('HEARTBEAT', 'Heartbeat'), ('LOAD_SUCCESS', 'Load success'), ('LOAD_ERROR', 'Load error'), ('LOW_MEMORY', 'Low memory'), ('APP_START', 'App start'), ('APP_RESUME', 'App resume'), ('APP_PAUSE', 'App pause'), ('APP_STOP', 'App stop'), ('WEBVIEW_INFO', 'WebView info'), ('CUSTOM', 'Custom')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='core.device')),
            ],
            options={
                'verbose_name': 'Device telemetry event',
                'verbose_name_plural': 'Device telemetry events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_device_event_t_7e5f82_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_device_ip_addr_f07bc2_idx')],
            },
        ),
    ]
