# Generated by Django 5.0.14 on 2026-03-23 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_scraperhealth_notification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('command_name', models.CharField(max_length=120)),
                ('draw_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('validation_profile', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('incident', 'Incident')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('provider_scope', models.JSONField(blank=True, default=list)),
                ('expected_groups', models.JSONField(blank=True, default=list)),
                ('persisted_groups', models.JSONField(blank=True, default=list)),
                ('missing_groups', models.JSONField(blank=True, default=list)),
                ('failure_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('evidence_summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('incident_detected', models.BooleanField(default=False)),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper execution',
                'verbose_name_plural': 'Scraper executions',
                'ordering': ['-started_at', 'scraper_key'],
                'indexes': [models.Index(fields=['scraper_key', 'draw_date'], name='core_scrape_scraper_49819a_idx'), models.Index(fields=['status', 'draw_date'], name='core_scrape_status_41b0f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScraperIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('scraper_key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('command_name', models.CharField(max_length=120)),
                ('draw_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('draw_time', models.TimeField(blank=True, null=True)),
                ('result_model', models.CharField(blank=True, default='', max_length=64)),
                ('detection_scope', models.CharField(blank=True, default='', max_length=16)),
                ('validation_profile', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('severity', models.CharField(blank=True, default='critical', max_length=16)),
                ('failure_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('evidence_summary', models.TextField(blank=True, default='')),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.scraperexecution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_scraper_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scraper incident',
                'verbose_name_plural': 'Scraper incidents',
                'ordering': ['status', '-last_detected_at', 'scraper_key', 'provider_name'],
                'indexes': [models.Index(fields=['scraper_key', 'draw_date', 'status'], name='core_scrape_scraper_f29f0f_idx'), models.Index(fields=['provider_name', 'draw_date', 'status'], name='core_scrape_provide_a38a05_idx')],
            },
        ),
    ]
