# Generated by Django 5.0.14 on 2026-04-01 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cruzdailycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDeviceReport',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen semanal TV',
                'verbose_name_plural': 'Resumen semanal TV',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.device',),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='contingency_stage',
            field=models.CharField(choices=[('observing', 'Observing'), ('fallback_active', 'Fallback active'), ('manual_required', 'Manual required')], db_index=True, default='observing', max_length=24),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='fallback_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='fallback_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='fallback_scraper_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='manual_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperincident',
            name='primary_attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animalitoresult',
            name='result_origin',
            field=models.CharField(choices=[('automatic_valid', 'Automatic valid'), ('automatic_fallback', 'Automatic fallback'), ('manual_contingency', 'Manual contingency')], db_index=True, default='automatic_valid', max_length=32),
        ),
        migrations.AlterField(
            model_name='cruzdailycontent',
            name='draw_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='currentresult',
            name='result_origin',
            field=models.CharField(choices=[('automatic_valid', 'Automatic valid'), ('automatic_fallback', 'Automatic fallback'), ('manual_contingency', 'Manual contingency')], db_index=True, default='automatic_valid', max_length=32),
        ),
        migrations.AddIndex(
            model_name='scraperincident',
            index=models.Index(fields=['status', 'contingency_stage'], name='core_scrape_status_40b453_idx'),
        ),
    ]
