# Generated by Django 5.0.14 on 2026-04-06 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_weeklydevicereport_scraperincident_contingency_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplaySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rotation_seconds",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Duracion general de rotacion para tablas en la TV, expresada en segundos.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracion de pantalla TV",
                "verbose_name_plural": "Configuracion de pantalla TV",
            },
        ),
    ]
