from .client import Client
from .branch import Branch
from .device import Device
from .provider import Provider
from .current_result import CurrentResult
from .transmission import Transmission
from .license import License  
from .result_archive import ResultArchive
from .animalito_result import AnimalitoResult